# How to pick up drop item.
## 0 : Like vanilla. (If you approach to item, you can pick up it)
## 1 : Click then pick up. (PC: Right click, Mobile: Tap)
drop-item-pickup: 0

# Drop armor item style.
## 0 : Like be equipping it.
## 1 : Like an item.
armor-drop-style: 0

# If you pick up an armor, what if it does?
## 0 : Equip it instantly.
## 1 : Add it to inventory.
armor-equip-instantly: 0

# If you have any items not want to convert 3D object, add it.
# Only ID or "ID:META" notation is supported.
# If you write in "ID:META" format, do not forget the double quotation marks, like "35:14".
item-id-black-list: []